### ISSUE TITLE
Добавить настройку Гироскопа и Акселерометра 

### ISSUE THREAD

**Issue by khodand** [trikset/trik-webpanel#16]
Большая часть кода уже готова, но из-за появившихся проблем - отложили в дальний ящик

**Comment by anastasiia-kornilova** [comment]
@khodand, напиши, пожалуйста, что за проблемы, а то как-то не по существу.

**Comment by khodand** [comment]
При перезагрузке все выставленные настройки для ГиА сбрасываются к дефолтным. По крайней мере мы все были в этом уверены, когда этим занимались.

**Comment by iakov** [comment]
Так в чём проблема-то? Можно убрать это из секции `init` и сделать как-то иначе.  Давайте сделаем какой-то правильный скрипт в `/usr/share/trik/init.d/ `. Все скрипты оттуда вызываются при загрузке. Если в `/etc/default/trik` сохранять файл настроек в синтаксисе shell, то его можно будет просто использовать через `source`. В общем, давайте придумаем решение.
