### ISSUE TITLE
Add simple CI to project

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-webpanel#21]
- [x] Add WIP
- [ ] Shellcheck for cgi scripts 

Related to https://github.com/trikset/trik-webpanel/issues/5

**Comment by khodand** [comment]
https://www.codefactor.io/repository/github/trikset/trik-webpanel/trends/ratings/master
Я не уверен, что по этой ссылке можно что-то посмотреть. Но я не могу добавить плагин потому что мне не хватает прав
